### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" : "1374808356",
  "amount" : 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "c52454620a8f4d6a88e09bc58b41e6cb",
  "accountNumber" : "1000000000",
  "amount" : 30000
}

### query transaction
GET http://localhost:8080/transaction/de0ecb36f61f4f1dbebff5d3cd91f05d